### ISSUE TITLE
sentry.properties not found

### ISSUE THREAD

**Issue by pwnslinger** [snyk/java-call-graph-builder#43]
Hi,

After passing the `--reachable` flag to snyk-monitor, it looks sentry properties file. Since there's not such a file under the path, it throws the following error: 

```
SubprocessError: The command "'/Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/gradlew' printClasspath -I /usr/local/lib/node_modules/snyk/node_modules/@snyk/java-call-graph-builder/bin/init.gradle -q -p /Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/app" exited with code 1, Standard Error Output: /Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/sentry.properties (No such file or directory), /Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/sentry.properties (No such file or directory), /Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/sentry.properties (No such file or directory), /Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/sentry.properties (No such file or directory), /Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/sentry.properties (No such file or directory)
at ChildProcess.<anonymous> (/usr/local/lib/node_modules/snyk/node_modules/@snyk/java-call-graph-builder/lib/sub-process.ts:56:21)
at ChildProcess.emit (events.js:321:20)
at maybeClose (internal/child_process.js:1026:16)
at Socket.<anonymous> (internal/child_process.js:441:11)
at Socket.emit (events.js:321:20)
at Pipe.<anonymous> (net.js:668:12)
Error:
Monitoring /Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android...
```

In the build.gradle.kts file we have the following lines related to the sentry:

```config
plugins {
    id("com.android.application")
    id("kotlin-android")
   ...
    id("io.sentry.android.gradle")
    id("de.mannodermaus.android-junit5")
    jacoco

sentry {
    // Disables or enables the automatic configuration of ProGuard
    // for Sentry.  This injects a default config for ProGuard so
    // you don't need to do it manually.
    autoProguardConfig = true

    // Enables or disables the automatic upload of mapping files
    // during a build.  If you disable this, you'll need to manually
    // upload the mapping files with sentry-cli when you do a release.
    autoUpload = true

    // Disables or enables the automatic configuration of Native Symbols
    // for Sentry. This executes sentry-cli automatically so
    // you don't need to do it manually.
    // Default is disabled.
    uploadNativeSymbols = true

    // Does or doesn't include the source code of native code for Sentry.
    // This executes sentry-cli with the --include-sources param. automatically so
    // you don't need to do it manually.
    // Default is disabled.
    includeNativeSources = false
}

```

**Comment by pwnslinger** [comment]
To add more context to the debug information provided above, here is the result of running the Gradle dependency tree:

```
/Users/iosbuild/builds/XArs9oX-/0/varo-bank/mobile/android/varo-bank-android/sentry.properties (No such file or directory)
...
apolloProdDebugAndroidTestServiceDuplicatesConsumer
\--- project :graphql
apolloProdDebugServiceDuplicatesConsumer
\--- project :graphql
apolloProdDebugUnitTestServiceDuplicatesConsumer
\--- project :graphql
apolloProdReleaseServiceDuplicatesConsumer
\--- project :graphql
apolloProdReleaseUnitTestServiceDuplicatesConsumer
\--- project :graphql
apolloSitDebugAndroidTestServiceDuplicatesConsumer
\--- project :graphql
apolloSitDebugServiceDuplicatesConsumer
\--- project :graphql
apolloSitDebugUnitTestServiceDuplicatesConsumer
\--- project :graphql
apolloSitReleaseServiceDuplicatesConsumer
\--- project :graphql
apolloSitReleaseUnitTestServiceDuplicatesConsumer
\--- project :graphql
...
```

Here is the result of running call-graph-builder on the app:

```
$~> ./gradlew printClasspath -I /usr/local/lib/node_modules/snyk/node_modules/@snyk/java-call-graph-builder/bin/init.gradle -q -p ./app

/Users/iosbuild/builds/2TzqHy4i/0/varo-bank/mobile/android/varo-bank-android/sentry.properties (No such file or directory)
FAILURE: Build failed with an exception.
* Where:
Initialization script '/usr/local/lib/node_modules/snyk/node_modules/@snyk/java-call-graph-builder/bin/init.gradle' line: 4
* What went wrong:
Execution failed for task ':app:printClasspath'.
> Failed to apply plugin [id 'org.gradle.java']
> Cannot add task 'test' as a task with that name already exists.
```
